@startuml
interface IAttack {

}

abstract class AAttack {
}

class Piss {

}

class Shit {
}

class Toilet {
}

IAttack --|> AAttack
AAttack --|>  Piss
AAttack --|>  Shit
Piss --|> Toilet
Shit --|> Toilet
@enduml